version: "3.8"
services:
  postgres:
    image: postgis/postgis:15-3.3-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: bedflow
      POSTGRES_USER: bedflow
      POSTGRES_PASSWORD: bedflow
    ports: ["5432:5432"]
    volumes: ["pg_data:/var/lib/postgresql/data"]

  directus:
    image: directus/directus:10.11
    restart: unless-stopped
    environment:
      KEY: 255d861b70c2f4d3c8c0c8e5c7c2b8c4e5c8c0c8e5c7c2b8c4e5c8c0c8e5c7c2
      SECRET: 8c4e5c8c0c8e5c7c2b8c4e5c8c0c8e5c7c2b8c4e5c8c0c8e5c7c2b8c4e5c8c0
      DB_CLIENT: pg
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: bedflow
      DB_USER: bedflow
      DB_PASSWORD: bedflow
    ports: ["8055:8055"]
    depends_on: [postgres]

  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports: ["1883:1883"]
    volumes: ["./config/mosquitto.conf:/mosquitto/config/mosquitto.conf"]

  duckdb:
    image: python:3.11-slim
    restart: unless-stopped
    volumes:
      - "./data:/data"
      - "./scripts:/scripts"
    depends_on: [mosquitto]
    command: bash -c "pip install paho-mqtt duckdb && python /scripts/mqtt_to_duckdb.py"

volumes: { pg_data: {} }